# netlify.toml
[build]
command = "npm run build"
publish = ".next"

# Necessary settings for Next.js
[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"
NEXT_TELEMETRY_DISABLED = "1"

# Handle Next.js routes and static assets
[[plugins]]
package = "@netlify/plugin-nextjs"

# Enable Netlify Image CDN
[[plugins]]
package = "netlify-plugin-image-optim"

# Rewrite rules for SPA and API routes
[[redirects]]
from = "/*"
to = "/_next/static/:splat"
status = 200
force = true
conditions = { Path = "/_next/static/*" }

[[redirects]]
from = "/*"
to = "/api/:splat"
status = 200
force = true
conditions = { Path = "/api/*" }

[[redirects]]
from = "/*"
to = "/.netlify/functions/:splat"
status = 200
force = true
conditions = { Path = "/.netlify/functions/*" }

# Image optimization path
[[redirects]]
from = "/.netlify/images/*"
to = "/.netlify/image"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
